# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCnc2hrqkZne9vtxF9HGNZJZxmzsD8Gv

UMKM Go-Online — Full Pipeline
Step 1: Synthetic Data Generation (prior direvisi berdasarkan BPS E-Commerce 2023)
Step 2: Baseline ML Model (Logistic Regression + Random Forest + XGBoost)
Step 3: Evaluasi & SHAP Feature Importance

Referensi prior digitalisasi:
- BPS Statistik E-Commerce 2023 (bps.go.id)
  * WA/pesan instan: 95.33% (konteks: usaha yang SUDAH e-commerce → upper bound)
  * Media sosial: 33.29% (konteks sama → upper bound)
  * Website: 1.77% (populasi umum → dipakai langsung)
- LPEM FEB UI 2022 — Digitalisasi UMKM Indonesia
- Google/Temasek e-Conomy SEA 2023

Versi 2 — Label Deterministik (Opsi A) — FINAL
Perubahan dari v1:
1. Label is_go_online dibuat dengan aturan deterministik (base_prob per sektor×skala)
   bukan probabilistik murni → model punya pola yang bisa dipelajari
2. Gap base_prob antar sektor di Mikro_Lv1 diperlebar agar sinyal kuat
   (89% data adalah Mikro_Lv1, perlu diferensiasi yang jelas)
3. Fitur omset_pct ditambahkan (posisi omset dalam range skalanya)
4. One-Hot Encoding untuk fitur nominal (sektor, kapanewon) — lebih tepat dari LabelEncoder
5. Ordinal Encoding tetap untuk skala usaha (ada hierarki Lv1 < Lv2 < ... < Menengah)
6. Pipeline sklearn dipakai agar preprocessing konsisten antara train dan test

Referensi prior digitalisasi:
- BPS Statistik E-Commerce 2023 (bps.go.id)
  * WA/pesan instan: 95.33% (konteks: usaha SUDAH e-commerce -> upper bound)
  * Media sosial: 33.29% (konteks sama -> upper bound)
  * Website: 1.77% (populasi umum -> dipakai langsung)
- LPEM FEB UI 2022 — Digitalisasi UMKM Indonesia
- Google/Temasek e-Conomy SEA 2023
- Bank Indonesia (2022): UMKM skala Kecil/Menengah 3x lebih mungkin go-digital
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# %matplotlib inline

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, roc_curve, ConfusionMatrixDisplay)

"""# 1. SYNTHETIC DATA GENERATION"""

np.random.seed(42)
N = 5000

# Distribusi Kapanewon (dari PDF rekap Sleman)
kapanewon_dist = {
    "Gamping": 7975, "Godean": 8057, "Moyudan": 5345,
    "Minggir": 4436, "Seyegan": 6053, "Mlati": 7457,
    "Depok": 10769, "Berbah": 5139, "Prambanan": 5054,
    "Kalasan": 8016, "Ngemplak": 5977, "Ngaglik": 8389,
    "Sleman": 9407, "Tempel": 7490, "Turi": 4213,
    "Pakem": 4367, "Cangkringan": 2787,
}
kap_names  = list(kapanewon_dist.keys())
kap_totals = np.array(list(kapanewon_dist.values()), dtype=float)
kap_probs  = kap_totals / kap_totals.sum()

# Distribusi Skala Usaha (dari kolom Jumlah per Skala — PDF rekap)
skala_dist = {
    "Mikro_Lv1": 99314, "Mikro_Lv2": 9205, "Mikro_Lv3": 1675,
    "Mikro_Lv4": 408,   "Mikro_Lv5": 143,  "Kecil": 174, "Menengah": 11,
}
skala_names  = list(skala_dist.keys())
skala_totals = np.array(list(skala_dist.values()), dtype=float)
skala_probs  = skala_totals / skala_totals.sum()

# 3 Sektor fokus (sesuai brief lomba)
AGRI  = "Agribisnis"
JASA  = "Jasa"
DAGANG = "Perdagangan"

# Proporsi dari PDF: Pertanian=6877, JasaLainnya=34997, Perdagangan=29176
sektor_raw_count = {AGRI: 6877, JASA: 34997, DAGANG: 29176}
sek_names  = list(sektor_raw_count.keys())
sek_totals = np.array(list(sektor_raw_count.values()), dtype=float)
sek_probs  = sek_totals / sek_totals.sum()

# Range omset per skala (Rupiah/bulan, dari kolom omset PDF)
omset_range = {
    "Mikro_Lv1": (500_000,    4_999_999),
    "Mikro_Lv2": (5_000_000,  9_999_999),
    "Mikro_Lv3": (10_000_000, 24_999_999),
    "Mikro_Lv4": (25_000_000, 49_999_999),
    "Mikro_Lv5": (50_000_000, 99_999_999),
    "Kecil":     (100_000_000, 999_999_999),
    "Menengah":  (1_000_000_000, 4_999_999_999),
}

tenaga_kerja_range = {
    "Mikro_Lv1": (1, 4),   "Mikro_Lv2": (1, 6),
    "Mikro_Lv3": (2, 8),   "Mikro_Lv4": (3, 15),
    "Mikro_Lv5": (5, 19),  "Kecil": (20, 99), "Menengah": (100, 300),
}

# Prior Digitalisasi (BPS E-Commerce 2023)
p_wa = {AGRI: 0.22, JASA: 0.65, DAGANG: 0.50}
p_ig_given_wa = {AGRI: 0.12, JASA: 0.38, DAGANG: 0.30}
p_web_given_wa_ig = {AGRI: 0.03, JASA: 0.08, DAGANG: 0.06}

# Base probability go-online per kombinasi sektor x skala (aturan deterministik)
#
# Logika aturan:
# - Jasa (laundry, jastip): promosi via WA+IG sudah jadi kebutuhan utama
# - Perdagangan (kelontong): mulai sadar digital tapi masih banyak offline
# - Agribisnis: paling rendah — akses internet & literasi digital terbatas
#
# Gap antar sektor di Mikro_Lv1 SENGAJA diperlebar (0.04 / 0.18 / 0.09)
# karena 89% data ada di level ini — butuh sinyal yang kuat agar model bisa belajar.
# Referensi: BI (2022), BPS E-Commerce 2023, LPEM FEB UI (2022)

base_go_online_prob = {
    AGRI: {
        "Mikro_Lv1": 0.04,
        "Mikro_Lv2": 0.08,
        "Mikro_Lv3": 0.15,
        "Mikro_Lv4": 0.25,
        "Mikro_Lv5": 0.35,
        "Kecil":     0.50,
        "Menengah":  0.65,
    },
    JASA: {
        "Mikro_Lv1": 0.18,
        "Mikro_Lv2": 0.32,
        "Mikro_Lv3": 0.55,
        "Mikro_Lv4": 0.72,
        "Mikro_Lv5": 0.82,
        "Kecil":     0.90,
        "Menengah":  0.95,
    },
    DAGANG: {
        "Mikro_Lv1": 0.09,
        "Mikro_Lv2": 0.20,
        "Mikro_Lv3": 0.38,
        "Mikro_Lv4": 0.55,
        "Mikro_Lv5": 0.68,
        "Kecil":     0.80,
        "Menengah":  0.90,
    },
}

# Noise kecil agar data tidak terlalu "kotak-kotak" — tetap realistis
NOISE_STD = 0.04

def clamp(p, lo=0.01, hi=0.96):
    return max(lo, min(hi, p))

# Generate rows
rows = []
for _ in range(N):
    kapanewon = np.random.choice(kap_names,   p=kap_probs)
    skala     = np.random.choice(skala_names, p=skala_probs)
    sektor    = np.random.choice(sek_names,   p=sek_probs)

    lo, hi = omset_range[skala]
    omset  = np.random.randint(lo, hi + 1)
    omset_pct = (omset - lo) / (hi - lo)   # posisi relatif dalam range skala (0-1)

    lo_tk, hi_tk = tenaga_kerja_range[skala]
    total_tk     = np.random.randint(lo_tk, hi_tk + 1)
    tk_laki      = int(round(total_tk * np.random.uniform(0.45, 0.60)))
    tk_perempuan = total_tk - tk_laki

    # 1. Bikin bobot untuk lokasi (Urban vs Rural)
    urban_areas = ["Depok", "Mlati", "Gamping", "Ngaglik", "Kalasan"]
    lokasi_bonus = 0.15 if kapanewon in urban_areas else -0.05

    # 2. Bikin bobot untuk tenaga kerja (makin banyak TK = makin profesional)
    tk_bonus = (total_tk / 300) * 0.10  # max 0.10

    # Label deterministik: base_prob + kontribusi omset + noise kecil
    base_prob    = base_go_online_prob[sektor][skala]
    final_prob   = clamp(base_prob + (omset_pct * 0.08) + lokasi_bonus + tk_bonus + np.random.normal(0, NOISE_STD))
    is_go_online = int(np.random.random() < final_prob)

    # Indikator digital (konsisten dengan label, untuk EDA & validasi — BUKAN fitur ML)
    if is_go_online == 1:
        punya_wa      = 1
        punya_ig      = int(np.random.random() < 0.88)
        punya_website = int(np.random.random() < p_web_given_wa_ig[sektor] * 2)
    else:
        punya_wa      = int(np.random.random() < p_wa[sektor] * 0.45)
        punya_ig      = 0
        punya_website = 0

    digital_score = punya_wa + punya_ig + punya_website

    rows.append({
        "kapanewon":              kapanewon,
        "sektor_usaha":           sektor,
        "skala_usaha":            skala,
        "omset_per_bulan":        omset,
        "omset_pct_dalam_skala":  round(omset_pct, 4),
        "tenaga_kerja_total":     total_tk,
        "tenaga_kerja_laki":      tk_laki,
        "tenaga_kerja_perempuan": tk_perempuan,
        "punya_whatsapp":         punya_wa,
        "punya_instagram":        punya_ig,
        "punya_website":          punya_website,
        "digital_score":          digital_score,
        "is_go_online":           is_go_online,
    })

df = pd.DataFrame(rows)

print(f"\nDataset shape   : {df.shape}")
print(f"Go-Online (1)   : {df['is_go_online'].sum()} ({df['is_go_online'].mean()*100:.1f}%)")
print(f"Tidak G-O (0)   : {(df['is_go_online']==0).sum()} ({(df['is_go_online']==0).mean()*100:.1f}%)")
print("\nGo-Online rate per sektor:")
print(df.groupby("sektor_usaha")["is_go_online"].mean().apply(lambda x: f"{x*100:.1f}%"))
print("\nGo-Online rate per skala:")
go_per_skala = df.groupby("skala_usaha")["is_go_online"].mean() * 100
print(go_per_skala.reindex(skala_names).apply(lambda x: f"{x:.1f}%" if not np.isnan(x) else "N/A"))

df.to_csv("umkm_synthetic_sleman.csv", index=False)
print("\nDataset tersimpan sebagai umkm_synthetic_sleman.csv")

"""# 2. FEATURE ENGINEERING & PREPROCESSING"""

df_ml = df.copy()

# Skala usaha -> ordinal (BOLEH karena ada hierarki: Lv1 < Lv2 < ... < Menengah)
skala_order = {s: i for i, s in enumerate(skala_names)}
df_ml["skala_enc"] = df_ml["skala_usaha"].map(skala_order)

# Log omset — range omset sangat lebar, log lebih informatif
df_ml["log_omset"] = np.log1p(df_ml["omset_per_bulan"])

# Rasio tenaga kerja perempuan
df_ml["rasio_perempuan"] = (df_ml["tenaga_kerja_perempuan"]
                            / df_ml["tenaga_kerja_total"].replace(0, 1))

# Fitur kategorik nominal -> One-Hot Encoding
# Alasan: sektor & kapanewon tidak punya urutan numerik
CAT_FEATURES = ["sektor_usaha", "kapanewon"]
NUM_FEATURES  = [
    "skala_enc",
    "log_omset",
    "omset_pct_dalam_skala",
    "tenaga_kerja_total",
    "rasio_perempuan",
]
TARGET = "is_go_online"

X = df_ml[CAT_FEATURES + NUM_FEATURES]
y = df_ml[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

preprocessor = ColumnTransformer([
    ("ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False), CAT_FEATURES),
    ("num", StandardScaler(), NUM_FEATURES),
])

print(f"Train size : {X_train.shape[0]}")
print(f"Test size  : {X_test.shape[0]}")
print(f"Class balance (train) — 1: {y_train.sum()} | 0: {(y_train==0).sum()}")

"""# 3. TRAINING BASELINE MODELS"""

models = {
    "Logistic Regression": LogisticRegression(
        class_weight="balanced", max_iter=1000, C=0.5, random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200, class_weight="balanced", random_state=42
    ),
    "Gradient Boosting": GradientBoostingClassifier(
        n_estimators=150, learning_rate=0.08, random_state=42
    ),
}

results = {}

for name, model in models.items():
    print(f"\n {name}")

    pipe = Pipeline([("prep", preprocessor), ("clf", model)])
    pipe.fit(X_train, y_train)

    y_pred = pipe.predict(X_test)
    y_prob = pipe.predict_proba(X_test)[:, 1]

    auc = roc_auc_score(y_test, y_prob)
    cv  = cross_val_score(pipe, X_train, y_train, cv=5, scoring="roc_auc").mean()

    print(classification_report(y_test, y_pred, target_names=["Tidak GO", "GO Online"]))
    print(f"  ROC-AUC      : {auc:.4f}")
    print(f"  CV ROC-AUC   : {cv:.4f} (5-fold)")

    results[name] = {
        "pipe": pipe, "y_pred": y_pred, "y_prob": y_prob, "auc": auc, "cv_auc": cv
    }

best_name = max(results, key=lambda k: results[k]["auc"])
print(f"\nBest Model: {best_name} (AUC = {results[best_name]['auc']:.4f})")

"""# 4. VISUALISASI"""

fig, axes = plt.subplots(2, 3, figsize=(18, 11))
fig.suptitle("UMKM Go-Online — Baseline Model Report\n(Synthetic Data berbasis Rekap Sleman, BPS E-Commerce 2023)",
             fontsize=13, fontweight="bold", y=1.01)

colors = {"Logistic Regression": "#4C72B0",
          "Random Forest":       "#55A868",
          "Gradient Boosting":   "#C44E52"}

# Plot 1: ROC Curve
ax = axes[0, 0]
for name, res in results.items():
    fpr, tpr, _ = roc_curve(y_test, res["y_prob"])
    ax.plot(fpr, tpr, label=f"{name} (AUC={res['auc']:.3f})",
            color=colors[name], lw=2)
ax.plot([0,1],[0,1],"k--", lw=1, alpha=0.5)
ax.set_xlabel("False Positive Rate"); ax.set_ylabel("True Positive Rate")
ax.set_title("ROC Curve — Perbandingan Model")
ax.legend(fontsize=9); ax.grid(alpha=0.3)

# Plot 2: Confusion Matrix (best model)
ax = axes[0, 1]
best = results[best_name]
cm = confusion_matrix(y_test, best["y_pred"])
disp = ConfusionMatrixDisplay(cm, display_labels=["Tidak GO", "GO Online"])
disp.plot(ax=ax, colorbar=False, cmap="Blues")
ax.set_title(f"Confusion Matrix — {best_name}")

# Plot 3: Feature Importance (Random Forest, diagregasi per grup fitur)
ax = axes[0, 2]
rf_pipe = results["Random Forest"]["pipe"]
ohe_features = (rf_pipe.named_steps["prep"]
                .named_transformers_["ohe"]
                .get_feature_names_out(CAT_FEATURES)
                .tolist())
all_feature_names = ohe_features + NUM_FEATURES
rf_importances   = rf_pipe.named_steps["clf"].feature_importances_

feat_imp_dict = {}
feat_label_map = {
    "skala_enc":             "Skala Usaha",
    "log_omset":             "Log Omset",
    "omset_pct_dalam_skala": "Posisi Omset dlm Skala",
    "tenaga_kerja_total":    "Jumlah TK",
    "rasio_perempuan":       "Rasio TK Perempuan",
}
for fname, imp in zip(all_feature_names, rf_importances):
    if fname.startswith("sektor_usaha"):
        key = "Sektor Usaha"
    elif fname.startswith("kapanewon"):
        key = "Lokasi (Kapanewon)"
    else:
        key = feat_label_map.get(fname, fname)
    feat_imp_dict[key] = feat_imp_dict.get(key, 0) + imp

feat_series = pd.Series(feat_imp_dict).sort_values(ascending=True)
feat_series.plot(kind="barh", ax=ax, color="#55A868", edgecolor="white")
ax.set_title("Feature Importance (Random Forest)")
ax.set_xlabel("Importance Score")
ax.grid(axis="x", alpha=0.3)

# Plot 4: Go-Online Rate per Sektor
ax = axes[1, 0]
rate_sektor = df.groupby("sektor_usaha")["is_go_online"].mean() * 100
rate_sektor = rate_sektor.sort_values(ascending=False)
bars = ax.bar(rate_sektor.index, rate_sektor.values,
              color=["#4C72B0","#55A868","#C44E52"], edgecolor="white", width=0.5)
for bar, val in zip(bars, rate_sektor.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
            f"{val:.1f}%", ha="center", va="bottom", fontsize=10, fontweight="bold")
ax.set_title("Go-Online Rate per Sektor Usaha")
ax.set_ylabel("% Go-Online")
ax.set_ylim(0, max(rate_sektor.values) * 1.25)
ax.grid(axis="y", alpha=0.3)

# Plot 5: Go-Online Rate per Skala
ax = axes[1, 1]
rate_skala = df.groupby("skala_usaha")["is_go_online"].mean() * 100
rate_skala = rate_skala.reindex(skala_names)
ax.plot(rate_skala.index, rate_skala.values, marker="o", color="#C44E52",
        lw=2.5, markersize=8)
ax.fill_between(rate_skala.index, rate_skala.values, alpha=0.15, color="#C44E52")
ax.set_title("Go-Online Rate per Skala Usaha")
ax.set_ylabel("% Go-Online")
ax.set_xticklabels(rate_skala.index, rotation=30, ha="right")
ax.grid(alpha=0.3)

# Plot 6: Distribusi Digital Score
ax = axes[1, 2]
score_dist = df["digital_score"].value_counts().sort_index()
score_colors = ["#d62728", "#ff7f0e", "#2ca02c", "#1f77b4"]
score_labels = [
    f"Skor 0\n(Tidak ada platform)\n{score_dist.get(0,0)} UMKM",
    f"Skor 1\n(WA saja)\n{score_dist.get(1,0)} UMKM",
    f"Skor 2\n(WA + IG)\n{score_dist.get(2,0)} UMKM",
    f"Skor 3\n(WA + IG + Web)\n{score_dist.get(3,0)} UMKM",
]
ax.pie(
    score_dist.values, labels=score_labels, colors=score_colors,
    autopct="%1.1f%%", startangle=90, textprops={"fontsize": 8}
)
ax.set_title("Distribusi Digital Score UMKM")

plt.tight_layout()
plt.show()

# Summary tabel model
print("RINGKASAN PERFORMA MODEL")
print(f"{'Model':<25} {'AUC':>8} {'CV-AUC':>10}")
print("-" * 45)
for name, res in results.items():
    marker = " ← BEST" if name == best_name else ""
    print(f"{name:<25} {res['auc']:>8.4f} {res['cv_auc']:>10.4f}{marker}")